---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
# Defaults for role go-agent
#
GO_AGENT_SERVICE_NAME: "go-agent"
GO_AGENT_USER: "go"
GO_AGENT_GROUP: "{{ GO_AGENT_USER }}"
GO_AGENT_VERSION: "16.4.0-3223"
GO_AGENT_HOME: "/var/lib/go-agent/"
GO_AGENT_CONF_HOME: "/etc/default/"

# Java version settings
GO_AGENT_ORACLEJDK_VERSION: "7u80"
GO_AGENT_ORACLEJDK_BASE: "jdk1.7.0_80"
GO_AGENT_ORACLEJDK_BUILD: "b15"
GO_AGENT_ORACLEJDK_LINK: "/usr/lib/jvm/java-7-oracle"

# java tuning
GO_AGENT_JAVA_HOME: "{{ GO_AGENT_ORACLEJDK_LINK }}"

# Aptitude settings
GO_AGENT_APT_SOURCE: "deb https://download.go.cd /"
GO_AGENT_APT_KEY_URL: "https://download.go.cd/GOCD-GPG-KEY.asc"
GO_AGENT_APT_NAME: "go-agent"

# go-agent configuration settings
# override the server ip and port to connect an agent to it's go-server master.
GO_AGENT_SERVER_IP: 127.0.0.1
GO_AGENT_SERVER_PORT: 8153
