# Iterates over the data structure documented in tasks/main.yml
# checking out the grader code from the repository specified on
# a per queue basis.

- name: Checkout grader code
  git_2_0_1:
    repo: "{{ item.GIT_REPO }}"
    dest: "{{ xqwatcher_app_dir }}/data/{{ item.COURSE }}"
    version: "{{ item.GIT_REF }}"
    ssh_opts: "{{ xqwatcher_course_git_ssh_opts }}"
  with_items: "{{ XQWATCHER_COURSES }}"
  tags:
    - install
    - install:code
