---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
# Role includes for role analytics_api
#
# Example:
#
# dependencies:
#   - {
#   role: my_role
#   my_role_var0: "foo"
#   my_role_var1: "bar"
# }

dependencies:
  - common
  - supervisor
  - role: edx_service
    edx_service_name: "{{ analytics_api_service_name }}"
    edx_service_config: "{{ ANALYTICS_API_SERVICE_CONFIG }}"
    edx_service_repos: "{{ ANALYTICS_API_REPOS }}"
    edx_service_user: "{{ analytics_api_user }}"
    edx_service_home: "{{ analytics_api_home }}"
    edx_service_packages:
      debian: "{{ analytics_api_debian_pkgs }}"
      redhat: "{{ analytics_api_redhat_pkgs }}"
