---
tanguru_debian_pkgs:
  - openjdk-7-jre
  - unzip
  - libmysql-java
  - python-mysqldb
  - tomcat7 
  - libspring-instrument-java
  - xvfb
  - mailutils
  - postfix

tanaguru_download_link: "http://download.tanaguru.org/Tanaguru/tanaguru-3.1.0.i386.tar.gz"
# Go this link to find your desired ESR Firefox
# http://download-origin.cdn.mozilla.net/pub/firefox/releases/24.0esr/linux-x86_64/
# Default is en-US in our example
fixfox_esr_link: "http://download-origin.cdn.mozilla.net/pub/firefox/releases/24.0esr/linux-x86_64/en-US/firefox-24.0esr.tar.bz2"

TANAGURU_DATABASE_NAME: 'tgdatabase'
TANAGURU_DATABASE_USER: 'tguser'
TANAGURU_DATABASE_PASSWORD: 'tgPassword'
TANAGURU_URL: 'http://localhost:8080/tanaguru/'
TANAGURU_ADMIN_EMAIL: 'admin@example.com'
TANAGURU_ADMIN_PASSWORD: 'tanaguru15'

tanaguru_parameters:
  db_name: "{{ TANAGURU_DATABASE_NAME }}"
  db_user: "{{ TANAGURU_DATABASE_USER }}"
  db_password: "{{ TANAGURU_DATABASE_PASSWORD }}"
  url: "{{ TANAGURU_URL }}"
  admin_email: "{{ TANAGURU_ADMIN_EMAIL }}"
  admin_passwd: "{{ TANAGURU_ADMIN_PASSWORD }}"