---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role xsy
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#
- name: Create application user
  user:
    name: "{{ xsy_user }}"
    home: "{{ xsy_app_dir }}"
    createhome: no
    shell: /bin/false

- name: Create xsy user dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ xsy_user }}"
    group: "{{ common_web_group }}"
  with_items:
    - "{{ xsy_app_dir }}"
    - "{{ xsy_venvs_dir }}"

- name: Setup the xsy env
  template:
    src: "xsy_env.j2"
    dest: "{{ xsy_app_dir }}/xsy_env"
    owner: "{{ xsy_user }}"
    group: "{{ common_web_user }}"
    mode: "0644"
  notify: restart xsy

- name: Checkout the code
  git_2_0_1:
    dest: "{{ xsy_code_dir }}"
    repo: "{{ xsy_source_repo }}"
    version: "{{ xsy_version }}"
    accept_hostkey: yes
  become_user: "{{ xsy_user }}"
  register: xsy_checkout
  notify: restart xsy

- name: Install the requirements
  pip:
    requirements: "{{ xsy_requirements_file }}"
    virtualenv: "{{ xsy_venv_dir }}"
    state: present
    extra_args: "-i {{ COMMON_PYPI_MIRROR_URL }}"
  become_user: "{{ xsy_user }}"
  notify: restart xsy

- name: Create the supervisor wrapper
  template:
    src: "{{ xsy_supervisor_wrapper | basename }}.j2"
    dest: "{{ xsy_supervisor_wrapper }}"
    mode: "0755"
  become_user: "{{ xsy_user }}"
  notify: restart xsy

- name: Create a supervisor config
  template: 
    src: "xsy.conf.j2"
    dest: "{{ supervisor_available_dir }}/xsy.conf"
    owner: "{{ supervisor_user }}"
    group: "{{ supervisor_user }}"
  become_user: "{{ supervisor_user }}"
  notify: restart xsy

- name: Enable the supervisor config
  file:
    src: "{{ supervisor_available_dir }}/xsy.conf"
    dest: "{{ supervisor_cfg_dir }}/xsy.conf"
    state: link
    force: yes
    mode: "0644"
  become_user: "{{ supervisor_user }}"
  when: not disable_edx_services
  notify: restart xsy

- name: Update supervisor configuration
  shell:  "{{ supervisor_ctl }} -c {{ supervisor_cfg }} update"
  register: supervisor_update
  changed_when: supervisor_update.stdout is defined and supervisor_update.stdout != ""
  when: not disable_edx_services

- name: Ensure xsy is started
  supervisorctl:
    name: xsy
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    state: started
  when: not disable_edx_services

- include: tag_ec2.yml
  when: COMMON_TAG_EC2_INSTANCE
  tags:
    - deploy
