---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role newrelic-npi
# 

#
# vars are namespace with the module name.
#
newrelic-npi_role_name: newrelic-npi

#
# OS packages
newrelic-npi_debian_pkgs: []

newrelic-npi_redhat_pkgs: []

NEWRELIC_USER: 'newrelic'

# NPI
NEWRELIC_NPI_PREFIX: "/edx/app/npi/"
NEWRELIC_NPI_VERSION: "0.1.5"
NEWRELIC_NPI_PLATFORM: "linux"
NEWRELIC_NPI_ARCH: "x64"
NEWRELIC_NPI_DISTRO: "debian"
NEWRELCI_NPI_PLUGINS: []

newrelic_npi_installer: "platform_installer-{{ NEWRELIC_NPI_PLATFORM }}-{{ NEWRELIC_NPI_ARCH }}-v{{ NEWRELIC_NPI_VERSION }}.tar.gz"
NEWRELIC_NPI_URL: "https://download.newrelic.com/npi/v{{ NEWRELIC_NPI_VERSION }}/{{ newrelic_npi_installer }}"

