---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role server_utils
# 

#
# vars are namespaced with the module name.
#
server_utils_role_name: server_utils

#
# OS packages
#

server_utils_debian_pkgs:
  # not sure why this is installed
  - ack-grep
  # not sure why this is installed
  - mosh
  # not sure why this is installed
  # Not installed by default on vagrant ubuntu
  # boxes.
  # TODO: move to Vagrant role
  - curl
  - tree
  - screen
  - tmux
  - curl
  - vim-tiny
  - dnsutils
  - inetutils-telnet
  - netcat

server_utils_redhat_pkgs: []
