---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role docker
# 

#
# vars are namespaced with the module name.
#
docker_role_name: docker

#
# OS packages
#

docker_debian_pkgs: []

docker_redhat_pkgs: []
