---

- name: Get instance information
  action: ec2_facts

- name: Tag instance
  ec2_tag:
    resource: "{{ ansible_ec2_instance_id }}"
    region: "{{ ansible_ec2_placement_region }}"
    tags:
      "version:certs" : "{{ CERT_REPO }} {{ certs_checkout.after|truncate(7,True,'') }}"
  when: certs_checkout.after is defined
