---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo

  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q '.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - >
    [ -f /usr/lib/libsass.so ]
    && echo "File exists"
    || echo "File does not exists"