---
# Tests for this role


### Tests ###

# Sitespeed workers should have the latest version of firefox
# Lite test. Ensures we are not using
# the version of firefox specified in a different file.
- name: Verify firefox version
  shell: firefox --version
  register: firefox_version
- assert:
    that:
      - "'28.0' not in firefox_version.stdout"
