---
- name: create the supervisor config
  template:
    src: forum.conf.j2
    dest: "{{ supervisor_available_dir }}/forum.conf"
    owner: "{{ supervisor_user }}"
    group: "{{ supervisor_user }}"
    mode: 0644
  become_user: "{{ supervisor_user }}"
  register: forum_supervisor
  tags:
    - install
    - install:configuration

- name: enable the supervisor config
  file:
    src: "{{ supervisor_available_dir }}/forum.conf"
    dest: "{{ supervisor_cfg_dir }}/forum.conf"
    owner: "{{ supervisor_user }}"
    state: link
    force: yes
    mode: 0644
  become_user: "{{ supervisor_user }}"
  when: not disable_edx_services
  register: forum_supervisor
  tags:
    - install
    - install:configuration
  
- name: create the supervisor wrapper
  template:
    src: "{{ forum_supervisor_wrapper|basename }}.j2"
    dest: "{{ forum_supervisor_wrapper }}"
    mode: 0755
  become_user: "{{ forum_user }}"
  notify: restart the forum service
  tags:
    - install
    - install:configuration

- name: git checkout forum repo into {{ forum_code_dir }}
  git:
    dest: "{{ forum_code_dir }}"
    repo: "{{ forum_source_repo }}"
    version: "{{ forum_version }}"
    accept_hostkey: yes
  become_user: "{{ forum_user }}"
  register: forum_checkout
  notify: restart the forum service
  tags:
    - install
    - install:code

- name: install comments service bundle
  shell: "bundle install --deployment --path {{ forum_gem_root }} chdir={{ forum_code_dir }}"
  become_user: "{{ forum_user }}"
  environment: "{{ forum_environment }}"
  notify: restart the forum service
  tags:
    - install
    - install:app-requirements

  # call supervisorctl update. this reloads
  # the supervisorctl config and restarts
  # the services if any of the configurations
  # have changed.
  #


- include: test.yml
  tags:
    - deploy

- include: tag_ec2.yml
  when: COMMON_TAG_EC2_INSTANCE
  tags: 
    - deploy

- set_fact:
    forum_installed: true
