---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role container
# 

#
# vars are namespaced with the module name.
#
container_role_name: container

#
# OS packages
#

container_debian_pkgs: []

container_redhat_pkgs: []
