---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role xsy
# 

#
# vars are namespace with the module name.
#


XSY_USERNAME: '1234_1234@chat.hipchat.com'
XSY_PASSWORD: 'password'
XSY_V1_TOKEN: 'HIPCHAT_V1_TOKEN'
XSY_V2_TOKEN: 'HIPCHAT_V2_TOKEN'
XSY_WILL_ROOMS: 'Hammer'
XSY_NAME: 'xsy'
XSY_HANDLE: 'xsy'
XSY_REDIS_URL: 'redis://fakeuser:redispassword@localhost:6379'
XSY_HTTPSERVER_PORT: '8081'
XSY_WORLD_WEATHER_KEY: !!null


xsy_service_name: xsy

xsy_user: xsy
xsy_app_dir: "{{ COMMON_APP_DIR }}/xsy"
xsy_code_dir: "{{ xsy_app_dir }}/xsy"
xsy_venvs_dir: "{{ xsy_app_dir }}/venvs"
xsy_venv_dir: "{{ xsy_venvs_dir }}/xsy"
xsy_venv_bin: "{{ xsy_venv_dir }}/bin"

xsy_source_repo: "https://github.com/edx/xsy.git"
xsy_version: "HEAD"
xsy_requirements_file: "{{ xsy_code_dir }}/requirements.txt"

xsy_supervisor_wrapper: "{{ xsy_app_dir }}/xsy-supervisor.sh"

xsy_environment:
  WILL_USERNAME: "{{ XSY_USERNAME }}"
  WILL_PASSWORD: "{{ XSY_PASSWORD }}"
  WILL_V1_TOKEN: "{{ XSY_V1_TOKEN }}"
  WILL_V2_TOKEN: "{{ XSY_V2_TOKEN }}"
  WILL_NAME: "{{ XSY_NAME }}"
  WILL_HANDLE: "{{ XSY_HANDLE }}"
  WILL_REDIS_URL: "{{ XSY_REDIS_URL }}"
  WILL_HTTPSERVER_PORT: "{{ XSY_HTTPSERVER_PORT }}"
  WILL_WORLD_WEATHER_ONLINE_KEY: "{{ XSY_WORLD_WEATHER_KEY }}"
  WILL_ROOMS: "{{ XSY_WILL_ROOMS }}"


#
# OS packages
#

xsy_debian_pkgs: []

xsy_redhat_pkgs: []

