---
# Nat monitors should be defined as a list of dictionaries
# e.g.
# NAT_MONITORS:
#   - vpc_name: 'loadtest-edx'
#     region: 'us-east-1'
#     deployment: 'edx'
# 
# To receive E-mails, ses should be setup with the
# aws account that is defined by the JENKINS_ADMIN_MAIL_PROFILE
# and the from adress should be verified
# JENKINS_ADMIN_MAIL_PROFILE: 'aws_account_name'
# JENKINS_ADMIN_FROM_EMAIL: 'admin@example.com'
# JENKINS_ADMIN_TO_EMAIL: 'alert@example.com'


- fail: msg="NAT_MONITORS is not defined."
  when: NAT_MONITORS is not defined

- name: upload the monitor script
  copy:
    dest="{{ jenkins_admin_scripts_dir }}/nat-monitor.sh"
    src="nat-monitor.sh"
    owner="{{ jenkins_user }}"
    group="{{ jenkins_group }}"
    mode="755"
  become_user: "{{ jenkins_user }}"
  notify: restart nat monitor

- name: create a supervisor config
  template:
    src="nat-monitor.conf.j2" dest="{{ jenkins_supervisor_available_dir }}/nat-monitor.conf"
    owner="{{ jenkins_user }}"
    group="{{ jenkins_group }}"
  become_user: "{{ jenkins_user }}"
  notify: restart nat monitor

- name: enable the supervisor config
  file:
    src="{{ jenkins_supervisor_available_dir }}/nat-monitor.conf"
    dest="{{ jenkins_supervisor_cfg_dir }}/nat-monitor.conf"
    state=link
    force=yes
    mode=0644
  become_user: "{{ jenkins_user }}"
  when: not disable_edx_services
  notify: restart nat monitor

- name: update supervisor configuration
  shell:  "{{ jenkins_supervisor_ctl }} -c {{ jenkins_supervisor_cfg }} update"
  register: supervisor_update
  changed_when: supervisor_update.stdout is defined and supervisor_update.stdout != ""
  when: not disable_edx_services

# Have to use shell here because supervisorctl doesn't support
# process groups.
- name: ensure nat monitor is started
  shell: "{{ jenkins_supervisor_ctl }} -c {{ jenkins_supervisor_cfg }} start nat_monitor:*"
  when: not disable_edx_services
