---
- name: restart notifier-scheduler
  supervisorctl:
    name: "notifier-scheduler"
    state: restarted
    config: "{{ supervisor_cfg }}"
    supervisorctl_path: "{{ supervisor_ctl }}"
  when: not disable_edx_services

- name: restart notifier-celery-workers
  supervisorctl:
    name: "notifier-celery-workers"
    state: restarted
    config: "{{ supervisor_cfg }}"
    supervisorctl_path: "{{ supervisor_ctl }}"
  when: not disable_edx_services
