---
- name: Stop mysql service
  service: 
    name: mysql 
    state: stopped

- name: Remove experimental apt repository
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/ondrej/mysql-experimental/ubuntu precise main'
    state: absent

- name: Remove experimental version of mysql
  apt: 
    name: "{{ item }}" 
    state: absent 
    purge: yes
  with_items:
    - mysql-server-5.6
    - mysql-server