---
# User/group to manage Android SDK
android_user: "android"
android_group: "android"
# Tarball to download
android_download: "android-sdk_r24.4.1-linux.tgz"
# Checksum of Android SDK (from: https://developer.android.com/studio/index.html#downloads)
android_checksum: "725bb360f0f7d04eaccff5a2d57abdd49061326d"
# path to installed android sdk
android_home: "/opt/android-sdk-linux"
# individual android build targets to be downloaded via the android sdk manager
android_build_targets:
    - android-23
# other android dependencies that cannot be tested via the android sdk manager
android_tools:
    - platform-tools
    - build-tools-23.0.3
    - extra-google-m2repository
    - extra-android-m2repository
