---
# Configure a system for building the edx android application

# Configure a user/group to own/run the android sdk
- name: Create group for the user of the sdk
  group: name={{ android_group }} state=present
- name: Add the user to the group and configure shell
  user: name={{ android_user }} append=yes group={{ android_group }} shell=/bin/bash

# Download the Android SDK/tools tarball from Google's download site. 
# NOTE: while it is the general policy to use repositories/ppas as much as possible
#       it did not seem reliable for this work. Other avenues were explored:
#   - pre-Ubuntu 16 releases do not contain the android sdk in their apt repos
#   - the existing ppas containing the sdk are questionable
#   - ubuntu-make did not seem reliable at the time of writing this
- name: Download the Android SDK tarball
  get_url:
    url: "https://dl.google.com/android/{{ android_download }}"
    dest: /tmp/android-sdk.tgz
- name: Verify checksum of Android SDK
  shell: "sha1sum /tmp/android-sdk.tgz"
  register: sdk_checksum
- assert:
    that:
      "'{{ android_checksum }}' in sdk_checksum.stdout"
- name: Unarchive tarball to /opt/android-sdk
  unarchive:
    copy: no
    src: /tmp/android-sdk.tgz
    dest: /opt
    creates: "{{ android_home }}"
    owner: "{{ android_user }}"
    group: "{{ android_group }}" 
  become: yes
# Use the android sdk manager to install the build targets necessary for the edx mobile app
- name: Install Android API levels
  shell: "echo 'y' | {{ android_home }}/tools/android update sdk --no-ui --filter {{ ','.join(android_build_targets) }}"
  become: yes
  become_user: "{{ android_user }}"
# Use the android sdk manager to install the build tools necessary for the edx mobile app
- name: Install other Android tools
  shell: "echo 'y' | {{ android_home }}/tools/android update sdk --no-ui --filter {{ ','.join(android_tools) }}"
  become: yes
  become_user: "{{ android_user }}"
