---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role gocd
# 
# Example:
#
# dependencies:
#   - {
#   role: my_role 
#   my_role_var0: "foo"
#   my_role_var1: "bar"
# }

dependencies:
  - role: oraclejdk
    tags: java
    oraclejdk_version: "{{ GO_SERVER_ORACLEJDK_VERSION }}"
    oraclejdk_base: "{{ GO_SERVER_ORACLEJDK_BASE }}"
    oraclejdk_build: "{{ GO_SERVER_ORACLEJDK_BUILD }}"
    oraclejdk_link: "{{ GO_SERVER_ORACLEJDK_LINK }}"
