---
# Size of the desired swap file. Use a MB or GB suffix.
SWAPFILE_SIZE: 2GB
# SWAPFILE_LOCATION: Location of the swap file managed by this role.
SWAPFILE_LOCATION: /swapfile
# SWAPFILE_USE_DD: set this to True if your filesystem does not support 
# fallocate (e.g. if you use ext3). dd will then be used instead of fallocate.
SWAPFILE_USE_DD: False

#
# Advanced, optional settings: 
#

# SWAPFILE_SWAPPINESS: Update sysctl.conf to set the swappiness percentage
# (vm.swappiness) -- the lower it is, the less your system swaps memory pages.
# If this is False (default), no change will be made.
SWAPFILE_SWAPPINESS: False
# SWAPFILE_VFS_CACHE_PRESSURE: Update sysctl.conf to set the VFS cache pressure.
# "this percentage value controls the tendency of the kernel to reclaim the
#  memory which is used for caching of directory and inode objects."
# If this is False (default), no change will be made.
SWAPFILE_VFS_CACHE_PRESSURE: False
