---
- name: restart flower
  supervisorctl:
    state: restarted
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    name: "{{ FLOWER_USER }}"
  sudo_user: "{{ supervisor_service_user }}"
