---
#
# edX Configuration
#
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions

harprofiler_role_name: harprofiler

harprofiler_user: "harprofiler"
harprofiler_github_url: https://github.com/edx/harprofiler
harprofiler_version: master
harprofiler_dir: /edx/app/harprofiler
harprofiler_venv_dir: "{{ harprofiler_dir }}/venvs/harprofiler"
harprofiler_validation_script: validate_harprofiler_install.sh
