---
# Base role for installing requirements common between edxapp and edxlocal

edxapp_common_role_name: edxapp_common

# OS packages
edxapp_common_debian_pkgs:
    - build-essential
    - gfortran
    # Needed for sandboxes for CS188x classes :-(
    - graphviz
    - graphviz-dev
    - liblapack-dev
    - libmysqlclient-dev
    - libxml2-dev
    # for shapely
    - libgeos-dev
    - libxslt1-dev
    # for 18n
    - gettext
    # Pillow (PIL Fork) Dependencies
    # Needed by the CMS to manipulate images.
    - libjpeg8-dev
    - libpng12-dev
    # python-saml dependencies: (required for Shibboleth in third_party_auth)
    - libxmlsec1-dev
    - swig
