# Expects a list of dicts with these keys
#  - device: /dev/xvdk
#    mount: /edx/var/mongo
#    options: "defaults,noatime"
#    fstype: ext4
# While mount, options and fstype are pretty standard in our app, the device names
# will be highly dependent on how you stand up your instances.
#
# Additionally - order is important if you have child directories.  If you want to mount
# /edx/var/mongo and /edx/var/mongo/mongodb/journal, you must specify them in that order,
# otherwise this role will mount /edx/var/mongo over the top of /edx/var/mongo/mongodb/journal
# which is not what you wanted.
volumes: []

UNMOUNT_DISKS: false
