---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role docker
# 
# Overview:
#
# This is a special role for providing common, docker specific tasks.
#
# Dependencies:
#
# Inherits from the container role via meta/main.yml
# 
