---

oraclejdk_version: "8u65"
# what the archive unpacks to
oraclejdk_base: "jdk1.8.0_65"
oraclejdk_build: "b17"
oraclejdk_platform: "linux"
oraclejdk_arch: "x64"
oraclejdk_file: "jdk-{{ oraclejdk_version }}-{{ oraclejdk_platform }}-{{ oraclejdk_arch }}.tar.gz"
oraclejdk_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oraclejdk_version }}-{{ oraclejdk_build }}/{{ oraclejdk_file }}"
oraclejdk_link: "/usr/lib/jvm/java-8-oracle"

oraclejdk_debian_pkgs:
  - curl
